package com.tanabe.dh.nfl.team;

/**
 * Created by BTanabe on 5/28/2014.
 */
public enum NflTeamType {
    BILLS_TYPE,
    DOLPHINS_TYPE,
    PATRIOTS_TYPE,
    JETS_TYPE,
    RAVENS_TYPE,
    BENGALS_TYPE,
    BROWNS_TYPE,
    STEELERS_TYPE,
    TEXANS_TYPE,
    COLTS_TYPE,
    JAGUARS_TYPE,
    TITANS_TYPE,
    BRONCOS_TYPE,
    CHIEFS_TYPE,
    RAIDERS_TYPE,
    CHARGERS_TYPE,
    COWBOYS_TYPE,
    GIANTS_TYPE,
    EAGLES_TYPE,
    REDSKINS_TYPE,
    BEARS_TYPE,
    LIONS_TYPE,
    PACKERS_TYPE,
    VIKINGS_TYPE,
    FALCONS_TYPE,
    PANTHERS_TYPE,
    SAINTS_TYPE,
    BUCCANEERS_TYPE,
    CARDINALS_TYPE,
    RAMS_TYPE,
    FOURTYNINERS_TYPE,
    SEAHAWKS_TYPE,
    UNKNOWN_TYPE;
}
